### ISSUE TITLE
Classes are disjoint or no ?

### ISSUE THREAD

**Issue by aynesss** [LTTM/FedSpace#2]
I would like to know the meaning of `task_classes` in `load_training_data` method 

when I display task_classes , I find this :

`{0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 1: [10], 2: [11], 3: [12], 4: [13], 5: [14], 6: [15], 7: [16], 8: [17], 9: [18]}`
Can you please explain to me this result

**Comment by donaldssh** [comment]
task_classes is a dict where the key corresponds to the task id, and each task contains the list of classes corresponding to that task. With the default parameters used in the paper, task_classes should be:

`{0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 1: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 2: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 3: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], 4: [40, 41, 42, 43, 44, 45, 46, 47, 48, 49], 5: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59], 6: [60, 61, 62, 63, 64, 65, 66, 67, 68, 69], 7: [70, 71, 72, 73, 74, 75, 76, 77, 78, 79], 8: [80, 81, 82, 83, 84, 85, 86, 87, 88, 89], 9: [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]}`

In your example, you have 10 classes (class id from 0 to 9) assigned to task 0, while for each of the other tasks (from task id 1 to 9), you have only a single class assigned to them. For example in task 1 you have only the class 10, in task 2 the class 11 and so on.
